# Automatically build, run unit and integration tests to detect errors early (CI provided by GitHub)
# including making pull requests review easier

# Human-readable name in the actions tab
name: Java CI

# Build on every pull request regardless of the branch
# Wiki: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # temurin is the successor of adoptjdk
  JDK_DISTRIBUTION: 'temurin'
  JAVA_VERSION: 17

  JIB_VERSION: '0.9.0'
  JIB_CLI_DOWNLOAD: "https://github.com/GoogleContainerTools/jib/releases/download/v${{ env.JIB_VERSION }}-cli/jib-jre-${{ env.JIB_VERSION }}.zip"
  JIB_CHECKSUM: 'c0f47017f1218a223f51228cc69fe9d7793e600d8a05b11e4dbdba0dee6bfc11'

  BASE_IMAGE: 'gcr.io/distroless/java17-debian11:nonroot'

  # https://paper.readthedocs.io/en/latest/server/aikar-flags.html
  AIKAR_FLAGS: '-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions
  -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M
-XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4
-XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90
-XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem
-XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs
-Daikars.new.flags=true'
  JVM_FLAGS: '${{ env.AIKAR_FLAGS }} -server -XX:+ExitOnOutOfMemoryError'

jobs:
  # job id
  build_and_test:

    # Environment image - always use the newest OS
    runs-on: ubuntu-latest

    # Run steps
    steps:
      - name: Checkout PaperBox
        uses: actions/checkout@v2.4.0

      # Pull changes
      - name: Checkout Paper
        uses: actions/checkout@v2.4.0
        with:
          repository: PaperMC/Paper
          path: Paper
          ref: master

      # Cache only if the action is not run locally using act
      # https://github.com/nektos/act/issues/285#issuecomment-987550101
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        if: ${{ !env.ACT }}
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v2.5.0
        if: ${{ env.ACT }}
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download JIB
        run: |
          echo "Downloading JIB-Tool from ""$JIB_CLI_DOWNLOAD"
          wget --timestamping "$JIB_CLI_DOWNLOAD"
          # Security: verify the checksum with a pre-downloaded value to detect arbitary artifact replacement
          # or in transport modifications (MITM)
          echo "$JIB_CHECKSUM" "jib-jre-$JIB_VERSION.zip" | sha256sum --check -
          unzip "jib-jre-$JIB_VERSION.zip"

      - name: Patch and build
        run: |
          # Setup names for Git patching
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          # Change to the submodule folder
          cd Paper
          ./gradlew applyPatches --exclude-task test --exclude-task check --stacktrace
          # Create a full paperclip build
          ./gradlew createReobfPaperclipJar --exclude-task test --exclude-task check --stacktrace
          # stop daemon if both tasks are finished
          ./gradlew --stop

      - name: Extract vars
        run: |
          echo "Extracting versions"
          # Extract the Minecraft version
          echo "MC_VERSION=$(grep --perl-regexp --only-matching '(?<=mcVersion=)[0-9]\.[0-9]{2}(\.[0-9]{1,2})?' Paper/gradle.properties)" >> "$GITHUB_ENV"
          # Extract the Paper source code revision
          echo "REVISION=$(git -C Paper/ rev-parse --short HEAD | grep --extended-regexp "[0-9a-z]{4,56}")" >> "$GITHUB_ENV"
          # Extract the latest digest to include it in the metadata for reproducibility
          # Skopeo enables us to extract the data without pulling the image and having the correct
          # platform/architecture select. JIB will later download the image and uses it's own caching system
          echo "DIGEST=$(skopeo inspect docker://""$BASE_IMAGE"" | jq --raw-output '.Digest' | grep --extended-regexp "sha256:[a-z0-9]{64}")" >> "$GITHUB_ENV"

      - name: Extract jar
        run: |
          unzip Paper/build/libs/paper-paperclip*.jar -d Paper/build/libs/temp
          # Create dummy directory for the permission bug in JIB
          mkdir Paper/build/libs/temp/dummy

      - name: Build Container
        run: |
          export CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          # Create build file from an allow list of variables
          # Note the variables are not expanded here - see ' instead of "
          envsubst '$BASE_IMAGE:$DIGEST:$CREATED:$JVM_FLAGS:$REVISION:$MC_VERSION' < abstract-jib.yaml > jib.yaml 
          ./jib-"$JIB_VERSION"/bin/jib build \
            --additional-tags="$MC_VERSION" \
            --target docker://ghcr.io/games647/paperclip
