# Automatically build, run unit and integration tests to detect errors early (CI provided by GitHub)
# including making pull requests review easier

# Human-readable name in the actions tab
name: Java CI

# Build on every pull request regardless of the branch
# Wiki: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # job id
  build_and_test:

    # Environment image - always use the newest OS
    runs-on: ubuntu-latest

    # Run steps
    steps:
      # Pull changes
      - name: Checkout Paper
        uses: actions/checkout@v2.3.4
        with:
            repository: PaperMC/Paper
            path: Paper
            ref: master
#            token: ${{ secrets.UBERSHMEKEL_ALT_TOKEN }}

        # Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          # Use Java 16, because it's minimum required version by Geyser
          java-version: 17

      - name: Patch and build
        run: |
            git config --global user.email "no-reply@github.com"
            git config --global user.name "Github Actions"
            cd Paper
            ./gradlew applyPatches --stacktrace
            ./gradlew build --stacktrace
